# a web server for serving up all IOCs opi files
#
# each ioc supplies its own opi files to a shared volume and this
# service exposes those over HTTP

# TODO: supply some config to nginx like we use in K8S

services:

  epics-opis:
    image: docker.io/nginx:1.27.5

    restart: unless-stopped

    volumes:
      # mount this project's /opis into default nginx static html folder
      - ../../opi:/usr/share/nginx/html/opi:z
      - ./config/nginx.conf:/etc/nginx/nginx.conf:z

    security_opt:
      - label=disable

    platform: linux/amd64

    # expose http port 80 on host's 8001 (all NICs)
    ports:
      - 8001:80

    profiles:
      - deploy
      - test
